### ISSUE TITLE
Usage of descriptorType variable.

### ISSUE THREAD

**Issue by bmrocamora** [udacity/SFND_2D_Feature_Tracking#5]
In MidTermProject_Camera_Student.cpp, `descriptorType` variable is used twice with different meanings... This is bringing some confusion to students.

Line 128: `string descriptorType = "BRISK";`
Line 144: `string descriptorType = "DES_BINARY"; // DES_BINARY, DES_HOG`

Maybe change to `string descNormType = "DES_BINARY"; // DES_BINARY, DES_HOG` ?

**Comment by SudKul** [comment]
Hi @bmrocamora 
There has been a [minor update](https://github.com/udacity/SFND_2D_Feature_Tracking/commit/be672a4c157c29b690e2bb183e12d21051442698) in the starter code recently. 
Feel free to tweak the starter code as convenient to you. 
Thank you
