### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sparshgarg23** [udacity/SFND_2D_Feature_Tracking#7]
So I was able to build opencv4.1 (by downloading opencv4.1 and OpenCV-contrib) on ubuntu 16.04 and everything went fine. I also tried searching for the features2d package and was able to locate them under usr/local/include. Though in my case in the home directory I have created a separate folder in which I cloned the OpenCV git repo. Now when I try to build the project as mentioned in the following link(https://github.com/udacity/SFND_... I get the following error Fatal error: xfeatures2d.hpp no such file or directory What is strange is that when I go to the home folder in which OpenCV and OpenCV contribs are located I can find these files. Similarly, I can locate the library features2d in the usr/local/lib folder also. I tried to edit the cmakelist.txt file in the project by adding set("OPECV_DIR",/usr/local) but that didn't work. Any suggestions as to what can I do

**Comment by SudKul** [comment]
Hi @sparshgarg23 
Though we are a little late to respond, we encourage such _user-specific_ issues to be raised on the Knowledge hub, so that our experienced mentors can chime-in and new students can also learn from the discussion thread. 
Thank you

**Comment by sparshgarg23** [comment]
mr sudkul,rather than closing the issue abruptly without offering any advice it would have been better if you could have tried to offer some help.As for the issue being raised in KnowledgeHub,there was no response which is why the issue was raised here.
